In [ ]:
!pip install pymupdf pandas openpyxl rapidfuzz -q

import fitz
import pandas as pd
import re
from rapidfuzz import fuzz
from google.colab import files

uploaded = files.upload()

Saving teacher_guide.pdf to teacher_guide (1).pdf
Saving video_extracted_skills.csv to video_extracted_skills.csv

In [ ]:
pdf_path = [f for f in uploaded.keys() if f.lower().endswith(".pdf")][0]
csv_path = [f for f in uploaded.keys() if f.lower().endswith(".csv")][0]

df_lessons = pd.read_csv(csv_path)
df_lessons.head()

,file_name,unit_number,unit_title,lesson_number,lesson_title,skill,concept,learning_objective,difficulty_level,evidence_from_transcript
0,NA - الدرس 10 ｜ الوحدة4 ｜ وحدات قياس الطول ...,4,وحدات قياس الطول,10.0,التعرف على المتر والسنتيمتر والعلاقة بينهما,"التذكر, الملاحظة, استخدام الرموز والاختصارات ل...","المسطرة المترية, وحدة قياس المتر, وحدة قياس ال...","أن يتذكر الطالب مفهوم المسطرة المترية وقياسها,...",Easy,"ألاحظ المصطر المترية وأتذكر, نقول مصطر مترية ل..."
1,NA - -2021- الرياضيات ｜ الوحدة 1 ｜ التقريب ｜ ا...,1,التقريب,4.0,التقريب,مقارنة الأعداد ضمن 9999,مقارنة الأعداد، القيمة المنزلية (آحاد، عشرات، ...,أن يقارن الطالب بين عددين مكونين من أربع منازل...,Easy,السؤال يقول: أيهما أكبر، عدد المواليد الذكور أ...
2,NA - -2021- الرياضيات ｜ الوحدة 1 ｜ التقريب ｜ ا...,1,التقريب,4.0,التقريب,التقدير في المواقف الحياتية,التقريب كمفهوم للتقدير، عدم الحاجة للدقة المطل...,أن يفهم الطالب الحاجة إلى التقدير والتقريب في ...,Easy,ما عدد أوراق الأشجار التي في الصورة؟ ... هل نس...
3,NA - -2021- الرياضيات ｜ الوحدة 1 ｜ التقريب ｜ ا...,1,التقريب,4.0,التقريب,تحديد الأقرب في سياقات حياتية,مفهوم القرب والبعد كمدخل للتقريب.,أن يربط الطالب مفهوم القرب والبعد في الحياة ال...,Easy,إلى أي محطة سأذهب؟ ... المحطة الثانية؛ لأنها أ...
4,NA - -2021- الرياضيات ｜ الوحدة 1 ｜ التقريب ｜ ا...,1,التقريب,4.0,التقريب,تقريب الأعداد ضمن 9999,التقريب لأقرب 10، التقريب لأقرب 100، التقريب ل...,أن يقرب الطالب أعداداً ضمن 9999 إلى أقرب 10 و ...,Medium,يتوقع منا بعد الانتهاء من هذا الدرس أن نكون قا...

In [ ]:
lesson_col = "lesson_title"  # غيّريه حسب اسم العمود عندك
lessons = df_lessons[lesson_col].dropna().astype(str).tolist()

In [ ]:
def normalize_arabic(text):
    text = str(text)
    text = re.sub(r'[إأآا]', 'ا', text)
    text = re.sub(r'ى', 'ي', text)
    text = re.sub(r'ة', 'ه', text)
    text = re.sub(r'[ًٌٍَُِّْـ]', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

doc = fitz.open(pdf_path)

pages = []
for i, page in enumerate(doc):
    text = page.get_text("text")
    pages.append({
        "page_number": i + 1,
        "text": text,
        "norm_text": normalize_arabic(text)
    })

len(pages)

104

In [ ]:
patterns = {
    "unit_objectives": [
        "الاهداف",
        "مستويات الاهداف",
        "معرفه",
        "تطبيق",
        "استدلال"
    ],
    "conceptual_errors": [
        "الاخطاء المفاهيميه",
        "الخطا المفاهيمي",
        "اجراءات مقترحه للعلاج"
    ],
    "lesson_implementation": [
        "اليات تنفيذ الدرس",
        "اسم الدرس",
        "مرحله الاستعداد",
        "الاهداف التعليميه",
        "المهارات",
        "الخبرات السابقه",
        "المفاهيم الخاطئه المتوقعه",
        "العلاج",
        "اصول التدريس"
    ],
    "assessment": [
        "سلم تقدير عددي",
        "قائمه الرصد",
        "النشاط الكاشف",
        "مؤشرات الاداء"
    ]
}

patterns = {
    k: [normalize_arabic(x) for x in v]
    for k, v in patterns.items()
}

In [ ]:
results = []

for lesson in lessons:
    norm_lesson = normalize_arabic(lesson)

    for page in pages:
        text = page["norm_text"]

        lesson_score = fuzz.partial_ratio(norm_lesson, text)

        matched_sections = []

        for section_name, section_patterns in patterns.items():
            count = 0
            matched_words = []

            for p in section_patterns:
                if p in text:
                    count += 1
                    matched_words.append(p)

            if count > 0:
                matched_sections.append({
                    "section": section_name,
                    "matched_count": count,
                    "matched_words": matched_words
                })

        if lesson_score >= 70 or matched_sections:
            for sec in matched_sections:
                results.append({
                    "lesson_title": lesson,
                    "page_number": page["page_number"],
                    "lesson_match_score": lesson_score,
                    "section_type": sec["section"],
                    "matched_count": sec["matched_count"],
                    "matched_keywords": " | ".join(sec["matched_words"]),
                    "page_preview": page["text"][:500]
                })

results_df = pd.DataFrame(results)
results_df.head()

,lesson_title,page_number,lesson_match_score,section_type,matched_count,matched_keywords,page_preview
0,التعرف على المتر والسنتيمتر والعلاقة بينهما,3,55.813953,unit_objectives,1,معرفه,تــقــديــم\nيتصـف الҙإ صـلاح التربـوي ب�أنـه ...
1,التعرف على المتر والسنتيمتر والعلاقة بينهما,4,55.813953,unit_objectives,1,تطبيق,مــقــدمــة\nيُعدّ دليل المعلم متمّماً للصورة ...
2,التعرف على المتر والسنتيمتر والعلاقة بينهما,4,55.813953,lesson_implementation,1,المهارات,مــقــدمــة\nيُعدّ دليل المعلم متمّماً للصورة ...
3,التعرف على المتر والسنتيمتر والعلاقة بينهما,6,58.139535,unit_objectives,2,معرفه | تطبيق,2\n:نظريّات التعلّم\n الاتّجاه التقليدي في الف...
4,التعرف على المتر والسنتيمتر والعلاقة بينهما,7,55.813953,unit_objectives,1,معرفه,3\n:) الاتّجاه الحديث في التربية (النظرية البن...

In [ ]:
if not results_df.empty:
    results_df = results_df.sort_values(
        by=["lesson_title", "page_number", "matched_count", "lesson_match_score"],
        ascending=[True, True, False, False]
    )

results_df.to_csv("teacher_guide_detected_pages.csv", index=False, encoding="utf-8-sig")
files.download("teacher_guide_detected_pages.csv")

In [ ]:
summary_df = results_df.groupby(["lesson_title", "section_type"])["page_number"] \
    .apply(lambda x: sorted(set(x))) \
    .reset_index()

summary_df.to_csv("teacher_guide_pages_summary.csv", index=False, encoding="utf-8-sig")
files.download("teacher_guide_pages_summary.csv")

summary_df.head(20)

,lesson_title,section_type,page_number
0,الأعداد ضمن 9999,assessment,"[37, 38, 44, 45, 49, 50, 51, 56, 57, 58, 61, 6..."
1,الأعداد ضمن 9999,conceptual_errors,"[34, 41, 54, 59, 66, 73, 79, 86, 92]"
2,الأعداد ضمن 9999,lesson_implementation,"[4, 8, 19, 20, 21, 27, 28, 30, 35, 36, 42, 43,..."
3,الأعداد ضمن 9999,unit_objectives,"[3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 17, 18, 19,..."
4,الأعداد ضمن 99999,assessment,"[37, 38, 44, 45, 49, 50, 51, 56, 57, 58, 61, 6..."
5,الأعداد ضمن 99999,conceptual_errors,"[34, 41, 54, 59, 66, 73, 79, 86, 92]"
6,الأعداد ضمن 99999,lesson_implementation,"[4, 8, 19, 20, 21, 27, 28, 30, 35, 36, 42, 43,..."
7,الأعداد ضمن 99999,unit_objectives,"[3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 17, 18, 19,..."
8,التعرف على المتر والسنتيمتر والعلاقة بينهما,assessment,"[37, 38, 44, 45, 49, 50, 51, 56, 57, 58, 61, 6..."
9,التعرف على المتر والسنتيمتر والعلاقة بينهما,conceptual_errors,"[34, 41, 54, 59, 66, 73, 79, 86, 92]"
10,التعرف على المتر والسنتيمتر والعلاقة بينهما,lesson_implementation,"[4, 8, 19, 20, 21, 27, 28, 30, 35, 36, 42, 43,..."
11,التعرف على المتر والسنتيمتر والعلاقة بينهما,unit_objectives,"[3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 17, 18, 19,..."
12,التقريب,assessment,"[37, 38, 44, 45, 49, 50, 51, 56, 57, 58, 61, 6..."
13,التقريب,conceptual_errors,"[34, 41, 54, 59, 66, 73, 79, 86, 92]"
14,التقريب,lesson_implementation,"[4, 8, 19, 20, 21, 27, 28, 30, 35, 36, 42, 43,..."
15,التقريب,unit_objectives,"[3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 17, 18, 19,..."
16,الزّاوية وأنواعها,assessment,"[37, 38, 44, 45, 49, 50, 51, 56, 57, 58, 61, 6..."
17,الزّاوية وأنواعها,conceptual_errors,"[34, 41, 54, 59, 66, 73, 79, 86, 92]"
18,الزّاوية وأنواعها,lesson_implementation,"[4, 8, 19, 20, 21, 27, 28, 30, 35, 36, 42, 43,..."
19,الزّاوية وأنواعها,unit_objectives,"[3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 17, 18, 19,..."

In [ ]:
!pip install pandas rapidfuzz -q

import pandas as pd
import re
from rapidfuzz import fuzz
from google.colab import files

uploaded = files.upload()

Saving teacher_guide_detected_pages.csv to teacher_guide_detected_pages (1).csv
Saving teacher_guide_pages_summary.csv to teacher_guide_pages_summary (1).csv
Saving video_extracted_skills.csv to video_extracted_skills (1).csv

In [ ]:
guide_pages = pd.read_csv("teacher_guide_detected_pages (1).csv")
video_skills = pd.read_csv("video_extracted_skills (1).csv")

guide_pages.head(), video_skills.head()

(       lesson_title  page_number  lesson_match_score     section_type  \
 0  الأعداد ضمن 9999            3               56.25  unit_objectives
 1  الأعداد ضمن 9999            3               56.25  unit_objectives
 2  الأعداد ضمن 9999            3               56.25  unit_objectives
 3  الأعداد ضمن 9999            3               56.25  unit_objectives
 4  الأعداد ضمن 9999            3               56.25  unit_objectives

    matched_count matched_keywords  \
 0              1            معرفه
 1              1            معرفه
 2              1            معرفه
 3              1            معرفه
 4              1            معرفه

                                         page_preview
 0  تــقــديــم\nيتصـف الҙإ صـلاح التربـوي ب�أنـه ...
 1  تــقــديــم\nيتصـف الҙإ صـلاح التربـوي ب�أنـه ...
 2  تــقــديــم\nيتصـف الҙإ صـلاح التربـوي ب�أنـه ...
 3  تــقــديــم\nيتصـف الҙإ صـلاح التربـوي ب�أنـه ...
 4  تــقــديــم\nيتصـف الҙإ صـلاح التربـوي ب�أنـه ...  ,
                                            file_name unit_number  \
 0  NA - الدرس 10  ｜ الوحدة4 ｜   وحدات قياس الطول ...           4
 1  NA - -2021- الرياضيات ｜ الوحدة 1 ｜ التقريب ｜ ا...           1
 2  NA - -2021- الرياضيات ｜ الوحدة 1 ｜ التقريب ｜ ا...           1
 3  NA - -2021- الرياضيات ｜ الوحدة 1 ｜ التقريب ｜ ا...           1
 4  NA - -2021- الرياضيات ｜ الوحدة 1 ｜ التقريب ｜ ا...           1

          unit_title lesson_number  \
 0  وحدات قياس الطول          10.0
 1           التقريب           4.0
 2           التقريب           4.0
 3           التقريب           4.0
 4           التقريب           4.0

                                   lesson_title  \
 0  التعرف على المتر والسنتيمتر والعلاقة بينهما
 1                                      التقريب
 2                                      التقريب
 3                                      التقريب
 4                                      التقريب

                                                skill  \
 0  التذكر, الملاحظة, استخدام الرموز والاختصارات ل...
 1                            مقارنة الأعداد ضمن 9999
 2                        التقدير في المواقف الحياتية
 3                      تحديد الأقرب في سياقات حياتية
 4                             تقريب الأعداد ضمن 9999

                                              concept  \
 0  المسطرة المترية, وحدة قياس المتر, وحدة قياس ال...
 1  مقارنة الأعداد، القيمة المنزلية (آحاد، عشرات، ...
 2  التقريب كمفهوم للتقدير، عدم الحاجة للدقة المطل...
 3                  مفهوم القرب والبعد كمدخل للتقريب.
 4  التقريب لأقرب 10، التقريب لأقرب 100، التقريب ل...

                                   learning_objective difficulty_level  \
 0  أن يتذكر الطالب مفهوم المسطرة المترية وقياسها,...             Easy
 1  أن يقارن الطالب بين عددين مكونين من أربع منازل...             Easy
 2  أن يفهم الطالب الحاجة إلى التقدير والتقريب في ...             Easy
 3  أن يربط الطالب مفهوم القرب والبعد في الحياة ال...             Easy
 4  أن يقرب الطالب أعداداً ضمن 9999 إلى أقرب 10 و ...           Medium

                             evidence_from_transcript
 0  ألاحظ المصطر المترية وأتذكر, نقول مصطر مترية ل...
 1  السؤال يقول: أيهما أكبر، عدد المواليد الذكور أ...
 2  ما عدد أوراق الأشجار التي في الصورة؟ ... هل نس...
 3  إلى أي محطة سأذهب؟ ... المحطة الثانية؛ لأنها أ...
 4  يتوقع منا بعد الانتهاء من هذا الدرس أن نكون قا...  )

In [ ]:
def clean_text(text):
    text = str(text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def normalize_ar(text):
    text = str(text)
    text = re.sub(r'[إأآا]', 'ا', text)
    text = re.sub(r'ى', 'ي', text)
    text = re.sub(r'ة', 'ه', text)
    text = re.sub(r'[ًٌٍَُِّْـ]', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def extract_skills_from_text(text):
    text = clean_text(text)

    skill_patterns = [
        r"أن\s+يقرأ\s+الطالب[^.،\n]*",
        r"أن\s+يكتب\s+الطالب[^.،\n]*",
        r"أن\s+يمثل\s+الطالب[^.،\n]*",
        r"أن\s+يتعرف\s+الطالب[^.،\n]*",
        r"أن\s+يذكر\s+الطالب[^.،\n]*",
        r"أن\s+يقارن\s+الطالب[^.،\n]*",
        r"أن\s+يرتب\s+الطالب[^.،\n]*",
        r"أن\s+يقرب\s+الطالب[^.،\n]*",
        r"قراءة\s+[^.،\n]*",
        r"كتابة\s+[^.،\n]*",
        r"تمثيل\s+[^.،\n]*"
    ]

    skills = []
    for pattern in skill_patterns:
        matches = re.findall(pattern, text)
        skills.extend(matches)

    skills = [clean_text(s) for s in skills if len(clean_text(s)) > 10]
    skills = list(dict.fromkeys(skills))

    return skills

In [ ]:
guide_skills_rows = []

for _, row in guide_pages.iterrows():
    lesson = row["lesson_title"]
    page = row["page_number"]
    text = row.get("page_preview", "")

    skills = extract_skills_from_text(text)

    for skill in skills:
        guide_skills_rows.append({
            "lesson_title": lesson,
            "page_number": page,
            "guide_skill": skill,
            "guide_skill_norm": normalize_ar(skill)
        })

guide_skills_df = pd.DataFrame(guide_skills_rows)

guide_skills_df.to_csv("guide_extracted_skills.csv", index=False, encoding="utf-8-sig")
files.download("guide_extracted_skills.csv")

guide_skills_df.head()

,lesson_title,page_number,guide_skill,guide_skill_norm
0,الأعداد ضمن 9999,34,قراءة العدد بالطُّرق المختلفة āإذا كان āأحد āأ...,قراءه العدد بالطرق المختلفه āاذا كان āاحد āارق...
1,الأعداد ضمن 9999,34,تمثيل العدد على لوحة المنازل,تمثيل العدد علي لوحه المنازل
2,الأعداد ضمن 9999,34,تمثيل على المِعداد قد يخطئ الطا,تمثيل علي المعداد قد يخطئ الطا
3,الأعداد ضمن 9999,34,قراءة العدد بالطُّرق المختلفة āإذا كان āأحد āأ...,قراءه العدد بالطرق المختلفه āاذا كان āاحد āارق...
4,الأعداد ضمن 9999,34,تمثيل العدد على لوحة المنازل,تمثيل العدد علي لوحه المنازل

In [ ]:
!pip install pandas rapidfuzz -q

import pandas as pd
import re
from rapidfuzz import fuzz
from google.colab import files

guide_df = pd.read_csv("guide_extracted_skills.csv")
video_df = pd.read_csv("video_extracted_skills (1).csv")

guide_lesson_col = "lesson_title"
guide_skill_col  = "guide_skill"

video_lesson_col = "lesson_title"
video_skill_col  = "skill"

def normalize_ar(text):
    text = str(text)
    text = re.sub(r'[إأآاٱ]', 'ا', text)
    text = re.sub(r'ى', 'ي', text)
    text = re.sub(r'ة', 'ه', text)
    text = re.sub(r'[ًٌٍَُِّْـ]', '', text)
    text = re.sub(r'[^\w\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

guide_df["lesson_norm"] = guide_df[guide_lesson_col].apply(normalize_ar)
guide_df["skill_norm"] = guide_df[guide_skill_col].apply(normalize_ar)

video_df["lesson_norm"] = video_df[video_lesson_col].apply(normalize_ar)
video_df["skill_norm"] = video_df[video_skill_col].apply(normalize_ar)

comparison_rows = []
threshold = 75

for lesson_norm in guide_df["lesson_norm"].dropna().unique():

    guide_lesson = guide_df[guide_df["lesson_norm"] == lesson_norm]
    video_lesson = video_df[video_df["lesson_norm"] == lesson_norm]

    lesson_title = guide_lesson[guide_lesson_col].iloc[0]

    for _, g in guide_lesson.iterrows():

        best_score = 0
        best_video_skill = None

        for _, v in video_lesson.iterrows():
            score = fuzz.token_set_ratio(g["skill_norm"], v["skill_norm"])

            if score > best_score:
                best_score = score
                best_video_skill = v[video_skill_col]

        comparison_rows.append({
            "lesson_title": lesson_title,
            "guide_skill": g[guide_skill_col],
            "best_video_skill_match": best_video_skill,
            "similarity_score": best_score,
            "matched": best_score >= threshold
        })

comparison_df = pd.DataFrame(comparison_rows)

comparison_df.to_csv("skills_comparison_results.csv", index=False, encoding="utf-8-sig")
files.download("skills_comparison_results.csv")

comparison_df.head()

,lesson_title,guide_skill,best_video_skill_match,similarity_score,matched
0,الأعداد ضمن 9999,قراءة العدد بالطُّرق المختلفة āإذا كان āأحد āأ...,كتابة الأعداد المكونة من أربع منازل بالرموز من...,46.052632,False
1,الأعداد ضمن 9999,تمثيل العدد على لوحة المنازل,تمثيل الأعداد ضمن 9999 على لوحة المنازل,88.000000,True
2,الأعداد ضمن 9999,تمثيل على المِعداد قد يخطئ الطا,تمثيل الأعداد ضمن 9999 على المعداد,72.340426,False
3,الأعداد ضمن 9999,قراءة العدد بالطُّرق المختلفة āإذا كان āأحد āأ...,كتابة الأعداد المكونة من أربع منازل بالرموز من...,46.052632,False
4,الأعداد ضمن 9999,تمثيل العدد على لوحة المنازل,تمثيل الأعداد ضمن 9999 على لوحة المنازل,88.000000,True

In [ ]:
!pip install pandas rapidfuzz -q

import pandas as pd
import re
from rapidfuzz import fuzz
from google.colab import files

guide_df = pd.read_csv("guide_extracted_skills.csv")
video_df = pd.read_csv("video_extracted_skills (1).csv")

guide_lesson_col = "lesson_title"
guide_skill_col  = "guide_skill"

video_lesson_col = "lesson_title"
video_skill_col  = "skill"

In [ ]:
def normalize_ar(text):
    text = str(text)
    text = re.sub(r'[إأآاٱ]', 'ا', text)
    text = re.sub(r'ى', 'ي', text)
    text = re.sub(r'ة', 'ه', text)
    text = re.sub(r'[ًٌٍَُِّْـ]', '', text)
    text = re.sub(r'[^\w\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def split_skills(text):
    text = str(text)
    parts = re.split(r'،|,|؛|;|\n| و(?=أن )| و(?=\w)', text)
    parts = [p.strip() for p in parts if len(p.strip()) >= 8]
    return parts

def clean_skill_text(text):
    text = str(text).strip()
    text = re.sub(r'^(أن\s+)?', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

In [ ]:
guide_rows = []

for _, row in guide_df.iterrows():
    lesson = row[guide_lesson_col]
    skill_text = row[guide_skill_col]

    for skill in split_skills(skill_text):
        skill = clean_skill_text(skill)
        guide_rows.append({
            "lesson_title": lesson,
            "skill": skill,
            "skill_norm": normalize_ar(skill)
        })

guide_clean = pd.DataFrame(guide_rows)

guide_clean = guide_clean.drop_duplicates(
    subset=["lesson_title", "skill_norm"]
).reset_index(drop=True)

guide_clean.to_csv("guide_skills_cleaned.csv", index=False, encoding="utf-8-sig")
files.download("guide_skills_cleaned.csv")

guide_clean.shape

(1224, 3)

In [ ]:
video_rows = []

for _, row in video_df.iterrows():
    lesson = row[video_lesson_col]
    skill_text = row[video_skill_col]

    for skill in split_skills(skill_text):
        skill = clean_skill_text(skill)
        video_rows.append({
            "lesson_title": lesson,
            "skill": skill,
            "skill_norm": normalize_ar(skill)
        })

video_clean = pd.DataFrame(video_rows)

video_clean = video_clean.drop_duplicates(
    subset=["lesson_title", "skill_norm"]
).reset_index(drop=True)

video_clean.to_csv("video_skills_cleaned.csv", index=False, encoding="utf-8-sig")
files.download("video_skills_cleaned.csv")

video_clean.shape

(670, 3)

In [ ]:
comparison_rows = []
threshold = 75

for lesson in guide_clean["lesson_title"].dropna().unique():

    guide_lesson = guide_clean[guide_clean["lesson_title"] == lesson]
    video_lesson = video_clean[video_clean["lesson_title"].apply(normalize_ar) == normalize_ar(lesson)]

    for _, g in guide_lesson.iterrows():

        best_score = 0
        best_video_skill = None

        for _, v in video_lesson.iterrows():
            score = fuzz.token_set_ratio(g["skill_norm"], v["skill_norm"])

            if score > best_score:
                best_score = score
                best_video_skill = v["skill"]

        comparison_rows.append({
            "lesson_title": lesson,
            "guide_skill": g["skill"],
            "best_video_skill_match": best_video_skill,
            "similarity_score": best_score,
            "matched": best_score >= threshold
        })

comparison_df = pd.DataFrame(comparison_rows)

comparison_df.to_csv("skills_comparison_after_cleaning.csv", index=False, encoding="utf-8-sig")
files.download("skills_comparison_after_cleaning.csv")

comparison_df.head()

,lesson_title,guide_skill,best_video_skill_match,similarity_score,matched
0,الأعداد ضمن 9999,قراءة العدد بالطُّرق المختلفة āإذا كان āأحد āأ...,كتابة الأعداد المكونة من آلاف صحيحة بالرموز من...,51.282051,False
1,الأعداد ضمن 9999,حيث يُهملُ الطالب الصّفر,الأجسام الحسابية,48.648649,False
2,الأعداد ضمن 9999,يقرāأ العدد بدونه,إيجاد العدد السابق,57.142857,False
3,الأعداد ضمن 9999,تمثيل العدد على لوحة المنازل,تمثيل الأعداد ضمن 9999 على لوحة المنازل,88.000000,True
4,الأعداد ضمن 9999,تمثيل على المِعداد قد يخطئ الطا,تمثيل الأعداد ضمن 9999 على المعداد,72.340426,False

In [ ]:
lesson_accuracy = comparison_df.groupby("lesson_title").agg(
    guide_skills_count=("guide_skill", "count"),
    matched_skills_count=("matched", "sum"),
    average_similarity=("similarity_score", "mean")
).reset_index()

lesson_accuracy["coverage_accuracy"] = (
    lesson_accuracy["matched_skills_count"] / lesson_accuracy["guide_skills_count"]
) * 100

lesson_accuracy.to_csv("lesson_skill_accuracy_after_cleaning.csv", index=False, encoding="utf-8-sig")
files.download("lesson_skill_accuracy_after_cleaning.csv")

lesson_accuracy

,lesson_title,guide_skills_count,matched_skills_count,average_similarity,coverage_accuracy
0,الأعداد ضمن 9999,24,3,59.379990,12.500000
1,الأعداد ضمن 99999,24,5,60.547786,20.833333
2,التعرف على المتر والسنتيمتر والعلاقة بينهما,24,0,37.012774,0.000000
3,التقريب,24,0,50.581677,0.000000
4,الزّاوية وأنواعها,24,1,26.763095,4.166667
5,الشُّعاعُ والمستقيم,24,0,41.958221,0.000000
6,الضرب في العشرات,24,0,49.177309,0.000000
7,الضرب في العشرات تفاعلي,24,0,47.969522,0.000000
8,الضرب في المئات,24,1,45.950568,4.166667
9,الضرب في المئات ومضاعفاتها,24,0,45.171673,0.000000
10,القسمة (1),24,1,45.229935,4.166667
11,القسمة (2),24,0,51.145655,0.000000
12,القسمة على العدد 10,24,0,47.247206,0.000000
13,القيمة المنزلية,24,2,60.001824,8.333333
14,القيمة المنزليّة والصّورة الموسَّعة,24,0,47.554575,0.000000
15,الكسور,24,0,51.339946,0.000000
16,الكسور المتكافئة,24,0,47.373219,0.000000
17,المثلث,24,0,49.058005,0.000000
18,المجسمات,24,0,47.238922,0.000000
19,المحيط,24,1,44.227762,4.166667
20,المربع,24,0,47.868824,0.000000
21,المساحة,24,0,47.632003,0.000000
22,المقارنة بين الأعداد ضمن 9999,24,5,56.388802,20.833333
23,المقارنة بين الأعداد ضمن تسعة آلاف وتسع مئة وت...,24,1,50.525074,4.166667
24,تمثيل البيانات بالجداول,24,5,60.369300,20.833333
25,جمع عددين ضمن 9999 دون حمل,24,2,59.525749,8.333333
26,جمع عددين ضمن 9999 مع حمل,24,2,55.565135,8.333333
27,جمع عددين ضمن 99999,24,1,48.631174,4.166667
28,جمع وطرح الأعداد ضمن 9999,24,0,44.612402,0.000000
29,حقائق الضرب للعدد (4),24,0,51.922768,0.000000
30,حقائق الضرب للعدد (5),24,0,48.060168,0.000000
31,حقائق الضرب للعدد (6),24,0,46.296862,0.000000
32,حقائق الضرب للعدد (9),24,0,52.250623,0.000000
33,حقائق الضرب للعدد 2,24,0,51.139642,0.000000
34,حقائق الضرب للعدد 4,24,0,51.922768,0.000000
35,حقائق الضرب للعدد 7,24,0,50.771798,0.000000
36,حقائق الضرب للعدد 8,24,0,51.636184,0.000000
37,حقائق الضرب للعدد 9,24,0,52.250623,0.000000
38,حقائق الضرب للعدد ثلاثة,24,0,45.330843,0.000000
39,خصائص عملية الضرب,24,0,49.545603,0.000000
40,طرح عددين ضمن 9999 دون استلاف,24,1,51.875944,4.166667
41,طرح عددين ضمن 9999 مع استلاف,24,1,51.448834,4.166667
42,طرح عددين ضمن 9999 مع الاستلاف,24,1,50.629906,4.166667
43,طرح عددين ضمن 99999,24,0,47.171661,0.000000
44,قوانين الاحتمالات,24,0,44.906495,0.000000
45,معرض المجسمات,24,0,46.106597,0.000000
46,مقارنة الأعداد ضمن تسعة وتسعين ألفًا وتسعمئة و...,24,1,47.313836,4.166667
47,مقارنة الكسور,24,0,50.221153,0.000000
48,وحدات قياس الزمن,24,0,48.815517,0.000000
49,وحدات قياس الطول,24,1,48.037928,4.166667
50,وحدات قياس الكتلة,24,1,48.722007,4.166667

In [ ]:
!pip install -q google-generativeai pandas tqdm

In [ ]:
import pandas as pd
import google.generativeai as genai
from tqdm import tqdm
import json
import time
import re

# =========================
# 1. إعداد Gemini API
# =========================

GEMINI_API_KEY = "AQ.Ab8RN6J7Ih_DglGm5eAu0m_MoGVFJATMLvlFPBaRpd7Gdv_9VQ"

genai.configure(api_key=GEMINI_API_KEY)

model = genai.GenerativeModel("gemini-1.5-flash")

# =========================
# 2. تحميل الملفات
# =========================

video_df = pd.read_csv("/content/video_extracted_skills.csv")
guide_df = pd.read_csv("/content/guide_extracted_skills.csv")

# =========================
# 3. أسماء الأعمدة حسب ملفاتك
# =========================

VIDEO_LESSON_COL = "lesson_title"
VIDEO_SKILL_COL = "skill"
VIDEO_CONCEPT_COL = "concept"
VIDEO_OBJECTIVE_COL = "learning_objective"

GUIDE_LESSON_COL = "lesson_title"
GUIDE_SKILL_COL = "guide_skill"

# =========================
# 4. تنظيف بسيط للنصوص
# =========================

def clean_text(text):
    if pd.isna(text):
        return ""
    text = str(text).strip()
    text = re.sub(r"\s+", " ", text)
    return text

video_df[VIDEO_LESSON_COL] = video_df[VIDEO_LESSON_COL].apply(clean_text)
video_df[VIDEO_SKILL_COL] = video_df[VIDEO_SKILL_COL].apply(clean_text)
video_df[VIDEO_CONCEPT_COL] = video_df[VIDEO_CONCEPT_COL].apply(clean_text)
video_df[VIDEO_OBJECTIVE_COL] = video_df[VIDEO_OBJECTIVE_COL].apply(clean_text)

guide_df[GUIDE_LESSON_COL] = guide_df[GUIDE_LESSON_COL].apply(clean_text)
guide_df[GUIDE_SKILL_COL] = guide_df[GUIDE_SKILL_COL].apply(clean_text)

# =========================
# 5. دالة استخراج JSON
# =========================

def extract_json(text):
    text = text.strip()
    text = text.replace("```json", "").replace("```", "").strip()

    try:
        return json.loads(text)
    except:
        match = re.search(r"\{.*\}", text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group())
            except:
                pass

    return {
        "match_status": "Parsing Error",
        "best_video_skill": "",
        "confidence": 0.0,
        "reason": text
    }

# =========================
# 6. دالة المقارنة بالذكاء الاصطناعي
# =========================

def ai_compare_skill(guide_skill, video_items):
    video_text = "\n\n".join(video_items)

    prompt = f"""
أنت خبير في تحليل مهارات الرياضيات للصف الثالث الأساسي ومقارنتها بدليل المعلم.

المهمة:
قارن مهارة دليل المعلم مع المهارات والمفاهيم والأهداف التعليمية المستخرجة من الفيديو.

مهارة دليل المعلم:
{guide_skill}

المحتوى المستخرج من الفيديو:
{video_text}

صنّف النتيجة إلى واحدة فقط من القيم التالية:

Exact Match
Semantic Match
Covered by General Skill
Covered by Learning Objective
Partial Match
Missing

تعريفات مهمة:
- Exact Match: نفس المهارة تقريبًا مذكورة في الفيديو.
- Semantic Match: المهارة موجودة بمعنى مشابه حتى لو بصياغة مختلفة.
- Covered by General Skill: مهارة الفيديو عامة لكنها تغطي مهارة الدليل التفصيلية.
- Covered by Learning Objective: الهدف التعليمي في الفيديو يغطي مهارة الدليل حتى لو لم تُذكر كمهارة صريحة.
- Partial Match: الفيديو يغطي جزءًا من المهارة فقط.
- Missing: لا توجد تغطية واضحة للمهارة.

مهم جدًا:
إذا كانت مهارة الفيديو عامة مثل "قراءة الأعداد بشكل صحيح"
ومهارة الدليل تفصيلية مثل "قراءة الأعداد التي تحتوي على صفر"
فصنّفها Covered by General Skill.

أرجع JSON فقط بهذا الشكل:

{{
  "match_status": "",
  "best_video_skill": "",
  "confidence": 0.0,
  "reason": ""
}}
"""

    try:
        response = model.generate_content(prompt)
        return extract_json(response.text)
    except Exception as e:
        return {
            "match_status": "API Error",
            "best_video_skill": "",
            "confidence": 0.0,
            "reason": str(e)
        }

# =========================
# 7. تنفيذ المقارنة لكل درس
# =========================

results = []

lessons = guide_df[GUIDE_LESSON_COL].dropna().unique()

for lesson in tqdm(lessons):

    guide_skills = guide_df[
        guide_df[GUIDE_LESSON_COL] == lesson
    ][GUIDE_SKILL_COL].dropna().unique().tolist()

    lesson_video = video_df[
        video_df[VIDEO_LESSON_COL] == lesson
    ]

    video_items = []

    for _, row in lesson_video.iterrows():
        item = f"""
المهارة: {row[VIDEO_SKILL_COL]}
المفهوم: {row[VIDEO_CONCEPT_COL]}
الهدف التعليمي: {row[VIDEO_OBJECTIVE_COL]}
"""
        video_items.append(item)

    for guide_skill in guide_skills:

        if len(video_items) == 0:
            results.append({
                "lesson_title": lesson,
                "guide_skill": guide_skill,
                "best_video_skill": "",
                "match_status": "Missing",
                "confidence": 0.0,
                "reason": "No video skills found for this lesson"
            })
            continue

        ai_result = ai_compare_skill(guide_skill, video_items)

        results.append({
            "lesson_title": lesson,
            "guide_skill": guide_skill,
            "best_video_skill": ai_result.get("best_video_skill", ""),
            "match_status": ai_result.get("match_status", ""),
            "confidence": ai_result.get("confidence", 0.0),
            "reason": ai_result.get("reason", "")
        })

        time.sleep(1)

# =========================
# 8. حفظ نتائج المقارنة
# =========================

results_df = pd.DataFrame(results)

results_df.to_csv(
    "/content/ai_skill_alignment_results.csv",
    index=False,
    encoding="utf-8-sig"
)

results_df.head()

  0%|          | 0/51 [00:00<?, ?it/s]WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 380.79ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.10ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.13ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 331.25ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.07ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.78ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.05ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 355.75ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.82ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.52ms
  2%|▏         | 1/51 [00:23<19:27, 23.36s/it]WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.00ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.00ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.94ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.43ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.86ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.30ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.45ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.46ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 329.97ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.85ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 331.01ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.66ms
  4%|▍         | 2/51 [00:47<19:21, 23.70s/it]WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.02ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.82ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 306.72ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.54ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.05ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.78ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.13ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.80ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 306.30ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 279.65ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 279.77ms
  6%|▌         | 3/51 [01:10<18:50, 23.56s/it]WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 355.84ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.82ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 306.38ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.29ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 356.00ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.53ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.31ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 355.77ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 355.70ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 355.76ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 356.07ms
  8%|▊         | 4/51 [01:34<18:31, 23.65s/it]WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.76ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.88ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 306.66ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.22ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.96ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.64ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.12ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.92ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.97ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.66ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.58ms
 10%|▉         | 5/51 [01:57<18:04, 23.59s/it]WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.29ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.10ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.77ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.58ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.77ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.37ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.90ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.78ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.16ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.19ms
 12%|█▏        | 6/51 [02:21<17:35, 23.47s/it]WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.80ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.50ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.03ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.06ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.17ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.01ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.93ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 306.30ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.48ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.95ms
 14%|█▎        | 7/51 [02:44<17:08, 23.37s/it]WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.87ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.04ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.43ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.45ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.71ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.37ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.43ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.98ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.50ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.67ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.16ms
 16%|█▌        | 8/51 [03:07<16:47, 23.43s/it]WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.38ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.79ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.55ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.35ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.75ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.96ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.68ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.58ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.45ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 356.12ms
 18%|█▊        | 9/51 [03:31<16:21, 23.36s/it]WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.22ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 279.46ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.10ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 356.07ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.90ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 306.65ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.97ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.05ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.93ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 306.06ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.90ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.16ms
 20%|█▉        | 10/51 [03:54<16:03, 23.49s/it]WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.27ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.48ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.39ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 306.51ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.68ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.92ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.99ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.20ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.87ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.56ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.54ms
 22%|██▏       | 11/51 [04:18<15:38, 23.47s/it]WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 331.00ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.38ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 331.11ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 308.92ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 306.03ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.41ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.56ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.46ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.85ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.06ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 331.07ms
 24%|██▎       | 12/51 [04:41<15:17, 23.52s/it]WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.16ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 279.42ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 279.92ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.62ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.12ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.94ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.89ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.55ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 306.34ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.95ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.19ms
 25%|██▌       | 13/51 [05:05<14:52, 23.49s/it]WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.34ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 331.15ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.67ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 331.90ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 305.07ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.24ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.11ms
WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.45ms
WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 330.23ms

,lesson_title,guide_skill,best_video_skill,match_status,confidence,reason
0,الأعداد ضمن 9999,قراءة العدد بالطُّرق المختلفة āإذا كان āأحد āأ...,,API Error,0.0,400 POST https://generativelanguage.googleapis...
1,الأعداد ضمن 9999,تمثيل العدد على لوحة المنازل,,API Error,0.0,"('Connection aborted.', ConnectionResetError(1..."
2,الأعداد ضمن 9999,تمثيل على المِعداد قد يخطئ الطا,,API Error,0.0,400 POST https://generativelanguage.googleapis...
3,الأعداد ضمن 9999,كتابة الҙأعداد ضمن - āأنْ يتعرّف الطالب مفهوم ...,,API Error,0.0,"('Connection aborted.', ConnectionResetError(1..."
4,الأعداد ضمن 9999,تمثيل العدد على المعداد,,API Error,0.0,404 POST https://generativelanguage.googleapis...

In [ ]:
!pip install -q google-generativeai pandas tqdm

In [ ]:
import pandas as pd
import google.generativeai as genai
from tqdm import tqdm
import json
import time
import re

In [ ]:
GEMINI_API_KEY = "AQ.Ab8RN6LlAM50CeLBGotCQ5jjgL5AqkGHk07D2hY8m5hJM8j9SQ"

genai.configure(api_key=GEMINI_API_KEY)

model = genai.GenerativeModel("gemini-2.5-flash")

In [ ]:
video_df = pd.read_csv("/content/video_extracted_skills (1).csv")
guide_df = pd.read_csv("/content/guide_extracted_skills.csv")

In [ ]:
def clean_text(text):
    if pd.isna(text):
        return ""

    text = str(text)
    text = text.strip()

    text = re.sub(r"\s+", " ", text)

    return text

In [ ]:
for col in video_df.columns:
    video_df[col] = video_df[col].astype(str).apply(clean_text)

for col in guide_df.columns:
    guide_df[col] = guide_df[col].astype(str).apply(clean_text)

In [ ]:
def extract_json(text):

    text = text.replace("```json", "")
    text = text.replace("```", "")
    text = text.strip()

    match = re.search(r"\[.*\]", text, re.DOTALL)

    if match:
        text = match.group()

    return json.loads(text)

In [ ]:
def compare_lesson(lesson_name,
                   guide_skills,
                   video_records):

    guide_text = "\n".join([
        f"{i+1}. {s}"
        for i, s in enumerate(guide_skills)
    ])

    video_text = ""

    for i, row in enumerate(video_records):

        video_text += f"""

المهارة {i+1}
المهارة: {row['skill']}
المفهوم: {row['concept']}
الهدف التعليمي: {row['learning_objective']}

"""

    prompt = f"""
أنت خبير مناهج رياضيات.

لدي مهارات من دليل المعلم
ومهارات ومفاهيم وأهداف تعليمية مستخرجة من فيديو شرح الدرس.

اسم الدرس:
{lesson_name}

======================

مهارات دليل المعلم:

{guide_text}

======================

المحتوى المستخرج من الفيديو:

{video_text}

======================

لكل مهارة من دليل المعلم حدد:

Exact Match
Semantic Match
Covered by General Skill
Covered by Learning Objective
Partial Match
Missing

أرجع JSON Array فقط بالشكل التالي:

[
 {{
   "guide_skill":"",
   "best_video_skill":"",
   "match_status":"",
   "confidence":0.95,
   "reason":""
 }}
]

بدون أي نص إضافي.
"""

    response = model.generate_content(prompt)

    return extract_json(response.text)

In [ ]:
results = []

lessons = sorted(
    guide_df["lesson_title"].dropna().unique()
)

In [ ]:
for lesson in tqdm(lessons):

    guide_skills = guide_df[
        guide_df["lesson_title"] == lesson
    ]["guide_skill"].dropna().tolist()

    lesson_video = video_df[
        video_df["lesson_title"] == lesson
    ]

    if len(guide_skills) == 0:
        continue

    if len(lesson_video) == 0:
        continue

    video_records = lesson_video[
        [
            "skill",
            "concept",
            "learning_objective"
        ]
    ].to_dict("records")

    try:

        lesson_results = compare_lesson(
            lesson,
            guide_skills,
            video_records
        )

        for item in lesson_results:

            item["lesson_title"] = lesson

            results.append(item)

        time.sleep(2)

    except Exception as e:

        print("Error:", lesson)

        print(e)

  0%|          | 0/51 [00:00<?, ?it/s]ERROR:tornado.access:503 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1723.20ms
  2%|▏         | 1/51 [03:04<2:33:56, 184.72s/it]ERROR:tornado.access:503 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 2227.87ms
ERROR:tornado.access:503 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1571.74ms
ERROR:tornado.access:503 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 6931.32ms
ERROR:tornado.access:503 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1570.86ms
ERROR:tornado.access:503 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1318.08ms
ERROR:tornado.access:503 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1573.03ms
WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 432.96ms
  4%|▍         | 2/51 [03:28<1:13:36, 90.13s/it]

Error: الأعداد ضمن 99999
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 46.026584465s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 380.95ms
  6%|▌         | 3/51 [03:29<39:19, 49.16s/it]

Error: التعرف على المتر والسنتيمتر والعلاقة بينهما
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 45.642719245s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 560.39ms
  8%|▊         | 4/51 [03:29<23:28, 29.98s/it]

Error: التقريب
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 45.040311293s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 457.99ms
 10%|▉         | 5/51 [03:30<14:49, 19.34s/it]

Error: الزّاوية وأنواعها
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 44.569616809s.

ERROR:tornado.access:503 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 3315.23ms
 12%|█▏        | 6/51 [03:34<10:47, 14.38s/it]WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 462.07ms

Error: الشُّعاعُ والمستقيم
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 39.819643734s.

 14%|█▎        | 7/51 [03:35<07:13,  9.84s/it]WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 488.66ms

Error: الضرب في العشرات
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 39.306856744s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 636.73ms
 16%|█▌        | 8/51 [03:35<04:57,  6.92s/it]

Error: الضرب في العشرات تفاعلي
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 38.664136767s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 457.36ms
 18%|█▊        | 9/51 [03:36<03:25,  4.90s/it]

Error: الضرب في المئات
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 38.200737211s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 381.65ms
 20%|█▉        | 10/51 [03:36<02:23,  3.51s/it]

Error: الضرب في المئات ومضاعفاتها
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 37.793577975s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 407.12ms
 22%|██▏       | 11/51 [03:37<01:42,  2.57s/it]

Error: القسمة (1)
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 37.371688671s.

 24%|██▎       | 12/51 [03:37<01:15,  1.94s/it]WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 484.49ms

Error: القسمة (2)
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 36.864296516s.

 25%|██▌       | 13/51 [03:38<00:56,  1.48s/it]WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 407.61ms

Error: القسمة على العدد 10
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 36.444922821s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 509.07ms
 27%|██▋       | 14/51 [03:38<00:43,  1.19s/it]

Error: القيمة المنزلية
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 35.923089464s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 431.82ms
 29%|██▉       | 15/51 [03:39<00:34,  1.04it/s]

Error: القيمة المنزليّة والصّورة الموسَّعة
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 35.492402422s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 534.43ms
 31%|███▏      | 16/51 [03:39<00:29,  1.19it/s]

Error: الكسور
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 34.965392718s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 457.59ms
 33%|███▎      | 17/51 [03:40<00:24,  1.37it/s]

Error: الكسور المتكافئة
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 34.478572299s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 509.19ms
 35%|███▌      | 18/51 [03:40<00:21,  1.50it/s]

Error: المثلث
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 33.947858234s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 457.56ms
 37%|███▋      | 19/51 [03:41<00:19,  1.65it/s]

Error: المجسمات
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 33.483459879s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 406.42ms
 39%|███▉      | 20/51 [03:41<00:17,  1.82it/s]

Error: المحيط
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 33.068711173s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 509.26ms
 41%|████      | 21/51 [03:42<00:16,  1.84it/s]

Error: المربع
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 32.54540749s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 406.98ms
 43%|████▎     | 22/51 [03:42<00:14,  1.98it/s]

Error: المساحة
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 32.113895311s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 483.49ms
 45%|████▌     | 23/51 [03:43<00:14,  1.99it/s]

Error: المقارنة بين الأعداد ضمن 9999
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 31.631475398s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 431.81ms
 47%|████▋     | 24/51 [03:43<00:13,  2.06it/s]

Error: المقارنة بين الأعداد ضمن تسعة آلاف وتسع مئة وتسعة وتسعين
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 31.171221205s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 484.99ms
 49%|████▉     | 25/51 [03:43<00:12,  2.05it/s]

Error: تمثيل البيانات بالجداول
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 30.694679759s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 486.60ms
 51%|█████     | 26/51 [03:44<00:12,  2.03it/s]

Error: جمع عددين ضمن 9999 دون حمل
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 30.188040234s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 635.18ms
 53%|█████▎    | 27/51 [03:45<00:12,  1.86it/s]

Error: جمع عددين ضمن 9999 مع حمل
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 29.756074567s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 507.78ms
 55%|█████▍    | 28/51 [03:45<00:12,  1.88it/s]

Error: جمع عددين ضمن 99999
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 29.014094999s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 406.23ms
 57%|█████▋    | 29/51 [03:46<00:10,  2.01it/s]

Error: جمع وطرح الأعداد ضمن 9999
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 28.61232373s.

 59%|█████▉    | 30/51 [03:46<00:10,  2.03it/s]WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 459.49ms

Error: حقائق الضرب للعدد (4)
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 28.136926335s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 437.24ms
 61%|██████    | 31/51 [03:46<00:09,  2.08it/s]

Error: حقائق الضرب للعدد (5)
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 27.67235003s.

 63%|██████▎   | 32/51 [03:47<00:09,  2.05it/s]WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 489.70ms

Error: حقائق الضرب للعدد (6)
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 27.154073361s.

 65%|██████▍   | 33/51 [03:47<00:08,  2.06it/s]WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 461.39ms

Error: حقائق الضرب للعدد (9)
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 26.668543616s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 432.14ms
 67%|██████▋   | 34/51 [03:48<00:08,  2.11it/s]

Error: حقائق الضرب للعدد 2
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 26.2522921s.

 69%|██████▊   | 35/51 [03:48<00:07,  2.19it/s]WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 406.27ms

Error: حقائق الضرب للعدد 4
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 25.829518562s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 509.93ms
 71%|███████   | 36/51 [03:49<00:07,  2.10it/s]

Error: حقائق الضرب للعدد 7
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 25.298394495s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 536.43ms
 73%|███████▎  | 37/51 [03:49<00:06,  2.01it/s]

Error: حقائق الضرب للعدد 8
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 24.760083472s.

 75%|███████▍  | 38/51 [03:50<00:06,  2.08it/s]WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 432.43ms

Error: حقائق الضرب للعدد 9
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 24.301843422s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 510.62ms
 76%|███████▋  | 39/51 [03:50<00:05,  2.02it/s]

Error: حقائق الضرب للعدد ثلاثة
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 23.793469377s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 533.97ms
 78%|███████▊  | 40/51 [03:51<00:05,  1.96it/s]

Error: خصائص عملية الضرب
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 23.250060373s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 509.00ms
 80%|████████  | 41/51 [03:51<00:05,  1.95it/s]

Error: طرح عددين ضمن 9999 دون استلاف
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 22.705694944s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 484.91ms
 82%|████████▏ | 42/51 [03:52<00:04,  1.97it/s]

Error: طرح عددين ضمن 9999 مع استلاف
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 22.223968432s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 483.12ms
 84%|████████▍ | 43/51 [03:52<00:04,  1.98it/s]

Error: طرح عددين ضمن 9999 مع الاستلاف
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 21.71194081s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 485.87ms
 86%|████████▋ | 44/51 [03:53<00:03,  1.99it/s]

Error: طرح عددين ضمن 99999
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 21.229164502s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 483.85ms
 88%|████████▊ | 45/51 [03:53<00:03,  1.99it/s]

Error: قوانين الاحتمالات
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 20.723949902s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 508.94ms
 90%|█████████ | 46/51 [03:54<00:02,  1.97it/s]

Error: معرض المجسمات
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 20.20871333s.

 92%|█████████▏| 47/51 [03:54<00:01,  2.11it/s]WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 380.92ms

Error: مقارنة الأعداد ضمن تسعة وتسعين ألفًا وتسعمئة وتسعة وتسعين
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 19.804093606s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 535.41ms
 94%|█████████▍| 48/51 [03:55<00:01,  2.02it/s]

Error: مقارنة الكسور
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 19.25611534s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 458.63ms
 96%|█████████▌| 49/51 [03:55<00:00,  2.05it/s]

Error: وحدات قياس الزمن
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 18.790151514s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 584.32ms
 98%|█████████▊| 50/51 [03:56<00:00,  1.92it/s]

Error: وحدات قياس الطول
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 18.199377234s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 508.63ms
100%|██████████| 51/51 [03:56<00:00,  4.65s/it]

Error: وحدات قياس الكتلة
429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 17.671164773s.